### ISSUE TITLE
Verify working mutations

### ISSUE THREAD

**Issue by austinxewell** [austinxewell/adoptABLE#10]
work through mutations and verify that all are working correctly.

**Comment by austinxewell** [comment]
addAdoptedFamily is working and has been tested in graphql
deleteAdoptedFamily is working and has been tested in graphql

**Comment by Aphillip22** [comment]
addProduct is working and has been tested in graphql
deleteProduct is working and has been tested in graphql
addUser is working and has been tested in graphql
login is working and has been tested in graphql

**Comment by austinxewell** [comment]
all current required mutations are tested and working
