### ISSUE TITLE
Create Mutations (*optional* create category with relations) 

### ISSUE THREAD

**Issue by austinxewell** [austinxewell/adoptABLE#4]
Create mutations for Adoptee and Products

*Optional* create category to play products in
create mutations for products/categories.

**Comment by Aphillip22** [comment]
Created category and tag models + updated index.js and product model

**Comment by Aphillip22** [comment]
Added initial mutations, updated typeDefs

**Comment by Aphillip22** [comment]
User & product mutations complete

**Comment by austinxewell** [comment]
mutations have been implemented. closing issue.
